apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: uxayekvzs-go 
  janus-idp.io/tekton: uxayekvzs-go
  backstage.io/kubernetes-id: uxayekvzs-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uxayekvzs-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  